Add gradle kotlin dsl files detection

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -6,11 +6,11 @@ if [ -f $1/gradlew ]; then
 
 # Detect these Gradle specific files, so we can fail with a message
 # asking the user to enable the Gradle Wrapper for their project.
-elif [ -f $1/build.gradle ]; then
+elif [ -f $1/build.gradle ] || [ -f $1/build.gradle.kts ]; then
   echo "Gradle" && exit 0
-elif [ -f $1/settings.gradle ]; then
+elif [ -f $1/settings.gradle ] || [ -f $1/settings.gradle.kts ]; then
   echo "Gradle" && exit 0
 else
-  (>&2 echo "Could not find a 'gradlew' script or a 'build.gradle' file! Please check that they exist and are commited to Git.")
+  (>&2 echo "Could not find a 'gradlew' script or a 'build.gradle(.kts)' file! Please check that they exist and are commited to Git.")
   exit 1
 fi
