Revert changes to buildpack code

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,5 +1,12 @@
 #!/usr/bin/env bash
+# bin/test <build-dir> <env-dir> <artifact-dir>
 
-set -euo pipefail
+# fail fast
+set -e
 
-(cd "${1}" && ./gradlew --no-daemon check)
+GRADLE_CHECK_TASK=check
+if [ -n "${GRADLE_TESTPACK_LEGACY_TASK:-}" ]; then
+  GRADLE_CHECK_TASK=test
+fi
+
+cd ${1} && ./gradlew --gradle-user-home "$1/.gradle" --no-daemon "${GRADLE_CHECK_TASK}"
